# Generated by Django 4.1.7 on 2023-04-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_extraimage_product_extra_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/extra_images'),
        ),
    ]
