# Generated by Django 4.1.7 on 2023-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productsizequantity_delete_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
