# Generated by Django 4.1.7 on 2023-04-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productsize_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
