# Generated by Django 4.1.7 on 2023-04-23 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_sizes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('product', 'size')},
        ),
    ]
