# Generated by Django 4.1.7 on 2023-05-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_submails'),
    ]

    operations = [
        migrations.AddField(
            model_name='submails',
            name='confirm_token',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submails',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submails',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
