# Generated by Django 4.1.7 on 2023-04-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='size',
            new_name='selected_size',
        ),
    ]
