# Generated by Django 4.1.7 on 2023-04-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_size_orderitem_selected_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='selected_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
