# Generated by Django 4.1.7 on 2023-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В сборке', 'Processing'), ('Отправлен', 'Shipped')], default='В сборке', max_length=20),
        ),
    ]
