# Generated by Django 4.1.7 on 2023-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В сборке', 'В сборке'), ('Отправлен', 'Отправлен'), ('В архиве', 'В архиве')], default='В сборке', max_length=20),
        ),
    ]
